### ISSUE TITLE
[Safari] Link balloon is shown outside the view in manual tests if selection is collapsed

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-link#46] opened 2016-09-30 12:08 UTC
Test: [http://localhost:1030/build/modules/amd/tests/link/manual/link](http://localhost:1030/build/modules/amd/tests/link/manual/link).

When I click on the first word in editor, the link balloon is shown as below:
![Screen Shot 2016-09-30 at 14.03.10.png](https://codetreeusercontent.s3.amazonaws.com/uploads/12ca0d59-0587-4a61-8cf7-cce1f3354822/Screen+Shot+2016-09-30+at+14.03.10.png)

**Comment by pomek** [comment] 2016-09-30 12:37
It can be also reproduced in Chrome.

**Comment by maxbarnas** [comment] 2016-09-30 12:39
@pomek I'll update the title.

**Comment by oskarwrobel** [comment] 2016-09-30 12:41
Looks like a problem with getting offset of collapsed selection.
I can't reproduce it on Chrome.

**Comment by maxbarnas** [comment] 2016-09-30 12:44
@oskarwrobel Yep, I can't reproduce it either. @pomek, can you provide steps to reproduce it, along with version of Chrome, type of screen (retina, non-retina), zoom factor, and all that stuff?

**Comment by pomek** [comment] 2016-09-30 12:47
Eh. Yesterday I could reproduce it. Today I cannot. Maybe it was Firefox instead of Chrome. I am not sure. I would like to apologize for the mess.

**Comment by Reinmar** [comment] 2016-09-30 12:54
There's a ticket on review which fixes some cases in positioning – maybe that it will fix this issue.

**Comment by oskarwrobel** [comment] 2016-09-30 12:57
> There's a ticket on review which fixes some cases in positioning – maybe that it will fix this issue.

I'm afraid it is a different issue.

**Comment by Reinmar** [comment] 2016-09-30 13:01
Right... empty selection. I remember dealing with this in the past. It wasn't easy – I had to extend the range in some direction – otherwise the box was calculated incorrectly. And there were edge cases like empty blocks where the position had to be taken from the element.

**Comment by oskarwrobel** [comment] 2016-09-30 14:23
Here is a fix for this: https://github.com/ckeditor/ckeditor5-ui-default/issues/90

**Comment by Reinmar** [comment] 2017-05-03 16:39
Still as much reproducible as in the past. Could we fix it by positioning to the entire block if 0,0 cords were returned?

A full fix would be to inject an empty element inline in the place of the caret and positioning according to it. This may be required later on when we'll deal with scrolling to the caret on <kbd>Enter</kbd>, <kbd>Delete</kbd>, etc. but this is much more work.

**Comment by oleq** [comment] 2017-05-04 11:31
https://github.com/ckeditor/ckeditor5-utils/pull/154 should fix the issue.

**Closed** 2017-05-04 12:36 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
