### ISSUE TITLE
Unlink toolbar button is enabled when selection is not inside link element

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-link#93] opened 2017-04-05 16:17 UTC
![apr-05-2017 18-16-09](https://cloud.githubusercontent.com/assets/1057056/24715548/003377bc-1a2c-11e7-9fc8-ed8eb07851fd.gif)

**Comment by oleq** [comment] 2017-04-13 08:54
The super strange thing is that is starts working as soon as the first link is created:
![kapture 2017-04-13 at 10 53 30](https://cloud.githubusercontent.com/assets/1099479/24997607/830a7c42-2037-11e7-952f-aaa6b3adef4d.gif)

**Comment by oskarwrobel** [comment] 2017-04-13 08:57
When selection is placed inside link element for the first time.

**Comment by oskarwrobel** [comment] 2017-04-13 08:59
Maybe something related to `bind()` ?

**Comment by oleq** [comment] 2017-04-13 09:03
Hard to tell without debugging. This is really odd.

**Comment by oskarwrobel** [comment] 2017-04-13 09:07
This is because of missing initial `refreshState()` call in `UnlinkCommand`
https://github.com/ckeditor/ckeditor5-link/blob/master/src/unlinkcommand.js#L27

**Comment by oleq** [comment] 2017-04-18 12:37
We may not need it at all https://github.com/ckeditor/ckeditor5-link/issues/52#issuecomment-294822077 ;-)

**Comment by oleq** [comment] 2017-05-15 09:27
It turned out the issue is in `ToggleAttributeCommand`. Will be resolved in  https://github.com/ckeditor/ckeditor5-core/issues/50.

**Comment by Reinmar** [comment] 2017-05-15 09:45
I've just noticed that the LinkCommand doesn't base on ToggleAttributeCommand :D So no, this won't be fixed by the fix in the core.

**Comment by oleq** [comment] 2017-05-15 09:59
@Reinmar I guess [this one](https://github.com/ckeditor/ckeditor5-core/blob/t/50/src/editor/editor.js#L94-L98) should fix it.

**Comment by Reinmar** [comment] 2017-05-15 10:08
Not entirely. If you start the editor content with an image (link starts disabled) and then move the selection somewhere into a text, the link is not enabled because it's not refreshed.

**Comment by oleq** [comment] 2017-05-15 10:09
Shouldn't https://github.com/ckeditor/ckeditor5-core/pull/81/files#diff-2647a477d39df248744db49b8051e2e8R48 handle this case?

**Comment by Reinmar** [comment] 2017-05-15 10:12
No. LinkCommand doesn't inherit from TAC. Hence, we need the same fix in LC as you proposed in TAC.

**Comment by oleq** [comment] 2017-05-15 10:14
You're right. Shouldn't it rather become a core feature? I mean, there will be tons of commands experiencing the same issue in the future and it's easy to forget about this case.

**Comment by Reinmar** [comment] 2017-05-15 10:22
I guess we could have a helper (`core/command/helpers`) called `refreshOnChange()` which would add such listener. OTOH, these are 4 LOC and we also have a ticket in the engine opened (https://github.com/ckeditor/ckeditor5-engine/issues/698) which may affect (shorten) this code. So, I'd not do anything now. It's easier to repeat ourselves for now rather than fixing broken abstraction later on.  But I definitely agree that before 1.0.0 we'll need to clean this up.

**Closed** 2017-05-19 14:50 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug
